apiVersion: v1
kind: Template
metadata:
  name: build-watcher-buildconfig
  annotations:
    description: >
      This is Thoth Build Watcher BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    openshift.io/display-name: 'Thoth Core: Build Watcher BuildConfig'
    version: 0.0.1
    tags: thoth,build-watcher,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Build Watcher BuildConfig, this template is meant to
      be used by Bots, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: build-watcher-buildconfig
    app: thoth
    component: build-watcher

parameters:
  - description: Name of the github repository for Thoth's Build Watcher
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/build-watcher'

  - description: Git reference to be used for Thoth's Build Watcher
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: >
      Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: build-watcher
      labels:
        app: thoth
        component: build-watcher
    spec:
      successfulBuildsHistoryLimit: 1
      failedBuildsHistoryLimit: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "build-watcher:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
      triggers:
        - type: ImageChange
          imageChange: {}
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
